### ISSUE TITLE
Enforce signed requests

### ISSUE THREAD

**Issue by johannesnagl** [cosenary/Instagram-PHP-API#126]
There is a new security mechanism in town:

http://developers.instagram.com/post/116410697261/publishing-guidelines-and-signed-requests

Don't know, if the old system with signed headers is fully deprecated.

Documentation of the feature:
https://instagram.com/developer/secure-api-requests/

**Comment by luizzgithub** [comment]
I change;
https://github.com/luizzgithub/Instagram-PHP-API/commit/d7168ea2948793b3165e3b57e6e352f51384a24d

**Comment by johannesnagl** [comment]
hi @luizzgithub! can you try to re-do the changes with the same settings @cosenary use to format his code? (i think there's a mismatch between spaces/tabs, or the indent level)

currently it's not obvious, which lines you have changed!

**Comment by agustinbaretto** [comment]
I have been receiving "No matching code" errors from Instagram when trying to grant permissions to new users to my app, do you think this might be the cause? In such case, shouldn't errors be of the type "signature error"? Has anyone had the same problem?

**Comment by alinberce** [comment]
@agustinbaretto I am having the same issues today. It seems that if I do the regular authorization and I return the access_token from the login page, instead of the code, I receive the correct access_token. I have no idea why this is happening.

**Comment by agustinbaretto** [comment]
@alinberce I solved my problem by changing my IP. It seems that it happens when you get blacklisted for some reason. I have already contacted Instagram and asked them why this might have happened but still had no reply from them.

**Comment by alinberce** [comment]
@agustinbaretto  thanks for your answer. After restarting my heroku server it worked but I can randomly see the error... so sometimes it works sometimes it does not. Since I have the client_id working with normal auth flow and POST operations also work, I find it weird to be blacklisted somehow right when they made changes in the API. The app has worked in the same way, same amount of users for months now. So my guess is that they did some changes to accommodate the new API and some things are not right. I saw that the problem appeared for others too. Right now I am using normal auth (the access_token is retuned by login, and not the code) and all post operations are made with normal instagram calls from my android app, not the server. The limits are low but at least it works until I make the changes to switch to Secure API.

@luizzgithub  Thank you very much for posting your changes. I am not familiar with PHP too much (I am an android dev) so your code helps me a lot.

**Comment by luizzgithub** [comment]
sorry , no time ;
@johannesnagl 

@alinberce  Thank you , for your feedback!
my new change:
https://github.com/luizzgithub/Instagram-PHP-API/blob/master/src/Instagram.php

**Comment by beeseenmedia** [comment]
i agree that luizzgithub solution works.

i added the _generateSig function, changed the _signHeader function and added the following lines before if(isset($params)...

$sig = $this->_generateSig($function, $params);

$params = array_merge(array('sig' => $sig), (array)$params);

**Comment by johannesnagl** [comment]
Any chance to get a working code in master before September, 1st, where the new security mechanism is required?

There are three pull requests at the moment:
#128 (red lights)
#141 (spin-off of #128, currently red lights due to coding guidelines) 
#159 (green lights)

**Comment by beeseenmedia** [comment]
luizzgithub solution works

**Comment by r0mdau** [comment]
Take a look @beeseenmedia commit : https://github.com/beeseenmedia/Instagram-PHP-API/commit/caf7699d2ccfd2d4e0b1c3a1fd3e59a4094d6ae1

**Comment by beeseenmedia** [comment]
yeah, I am using my commit beeseenmedia@caf7699  which is basically @luizzgithub solution, with a few changes which added max and min id support for a lot of function and made a lot of them authorized api calls.

**Comment by johannesnagl** [comment]
we went with https://github.com/cosenary/Instagram-PHP-API/pull/159 - highly recommended! thx to @jublo!

**Comment by jublo** [comment]
You’re welcome, @johannesnagl!

**Comment by vinkla** [comment]
Merged.
