### ISSUE TITLE
your code has been stolen

### ISSUE THREAD

**Issue by tiger-seo** [cosenary/Instagram-PHP-API#139]
I am developer too and I understand how this might be offensive.
https://github.com/Andreyco/Instagram-for-PHP/commit/4f6e3ca219938f8a1473f83e00574661b70a8292
Andrej Badin has stolen your work :(
Maybe GitHub can ban him and his repo, because clearly he has violated your license agreement.

**Comment by vinkla** [comment]
No problem; https://github.com/Andreyco/Instagram-for-PHP/pull/3

**Comment by Andreyco** [comment]
I am sorry for troubles.

@tiger-seo
Readme file states "Based on Instagram-PHP-API by Christian Metz." all time long (which is now replaced with original licence). Long time ago I patched with PSR4 with no response for couple of weeks. Since I needed this for longterm project I decided to register package which I maintain from that time (I/we could not afford to include package which wasn't maintained as actively at that time). Since then I added Laravel support, fixes, I have ongoing rewrite which encapsulates API call into objects, ... I haven't striped any history (go and list all the contributors), everything except licence. Please, consider your words.

**Comment by vinkla** [comment]
No problem at all. This is a open source community. Forking and tweaking projects is how it works. Thanks for adding the license back :)
