### ISSUE TITLE
Error: "This method requires an authenticated users access token"

### ISSUE THREAD

**Issue by thenbucs** [cosenary/Instagram-PHP-API#89]
Please help. I'm getting the message below when testing when testing "example/index.php"...

Fatal error: Uncaught exception 'Exception' with message 'Error: _makeCall() | users/self/media/recent - This method requires an authenticated users access token.' in /home/whychoos/public_html/feeds/master/src/Instagram.php:441 Stack trace: #0 /home/whychoos/public_html/feeds/master/src/Instagram.php(158): MetzWeb\Instagram\Instagram->_makeCall('users/self/medi...', true, Array) #1 /home/whychoos/public_html/feeds/master/example/success.php(35): MetzWeb\Instagram\Instagram->getUserMedia() #2 {main} thrown in /home/whychoos/public_html/feeds/master/src/Instagram.php on line 441

**Comment by robertark** [comment]
You're making a call that doesn't include an access token. If you have an access token (as a result from the OAuth call), you can set it via `$Instagram->setAccessToken($token)`

**Comment by robertark** [comment]
Actually, I just ran into this issue... after digging in, the `getUserMedia()` method appears to only use the auth if you're getting your OWN media... which doesn't make sense, because some users profiles are private and require the auth key (hence the thrown error). I'm submitting a pull request that will resolve this issue.

**Comment by cosenary** [comment]
Merged pull request cf6bb9fdff7ae2b79eee760901b670662faf1332. Thanks for your contribution!
